name: Automation Testing Manual Trigger

# This allows the workflow to be triggered manually from the GitHub Actions tab
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Select a projects"
        required: true
        type: choice
        options:
          - "dashboard-mobile"
          - "payment-gateway"

env:
  NODE_VERSION: 20

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run script automation
        run: yarn run test:${{ github.event.inputs.message }}

      - name: Send success message to Slack
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            *Automation testing completed successfully.*

            *Selected apps:* "${{ github.event.inputs.message }}"
            *Triggered by:* ${{ github.actor }}
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send failure message to Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            *Automation testing failed!.*

            *Selected apps*: "${{ github.event.inputs.message }}"
            *Triggered by*: ${{ github.actor }}
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow Run>
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
